### ISSUE TITLE
[Bug report]: Loading of SDDS with extensions turned on in chrome

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#1019]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components, @scania/theme-light

### Package versions

OLD Components 1.7.2, scania/theme-light v3.1.2

### Browser

Chrome

### Framework

React

### Reproduction steps

When a user has a extension installed called **Browser Redirection Extension** the user gets an error in the javascript from SDDS package.

How to see the error
1. Install extension
2. Go to https://myscania.test.cs.scania.com/#/home 
3. Click login
4. See the page is blank

it probably comes from the Flash of unstyled content(FOUC) solution 

### Code example

-

### Screenshots

https://user-images.githubusercontent.com/35451568/233577272-9466aea3-72a5-427f-b6f9-28603a372b2c.mov

### Expected behaviour

Make it possible to use this extension since it is from citrix it can be a bigger problem

### Console errors

caught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at https://mylogin.scania.com/auth/resources/mmch9/login/sss-ciam-theme/node_modules/@scania/components/dist/core.js:17:12
    at https://mylogin.scania.com/auth/resources/mmch9/login/sss-ciam-theme/node_modules/@scania/components/dist/core.js:18:3

### Contact information

marcus.mena.pacheco@scania.com

**Comment by mJarsater** [comment]
I am currently not able to replicate this issue. Please reopen this issue if the problem persists.
