### ISSUE TITLE
Improvement - possibility to add icon to the right when button is present

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#103]
> ![image](https://user-images.githubusercontent.com/1199101/111976997-8c998980-8b02-11eb-9ae5-2cf555abb335.png)
> Picture from Figma for Button and icon used at the same time. Icon is on the right. I think this style is missing.
> 
> * Can be added on next release
> * Please add a note / issue if added in next release

- Adding issue on this

_Originally posted by @mmexvr in https://github.com/scania-digital-design-system/sdds/issues/101#issuecomment-804016381_

[AB#686](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/686)

**Comment by mJarsater** [comment]
Since it's a html/css component this is possible today.
