### ISSUE TITLE
Bus, engine and trailer icons

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#1052]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Design

### What is your feature request?

I'd like Tegel to add icons for buses, engines and trailers to the library.
All of the above are tightly connected to our business and used across multiple systems.
Today there is no support for them, hence we are forced to use icons with different styles, or pictograms.

### Background

.

### Contact information

alex.lioliopoulos@scania.com

**Comment by alexandereneroth** [comment]
Thanks for your request Alex! 
I'll forward it to the team.

**Comment by mJarsater** [comment]
This feature request is added to our backlog, both design and development work is needed. If you have any further questions reach out to our PO, Johan Nilo.
