### ISSUE TITLE
Add deprecation warnings

### ISSUE THREAD

**Issue by lkritsimas** [scania-digital-design-system/sdds#1060]
I have had multiple Tegel users in my organization express some confusion around which packages actually belong to Tegel and which are legacy SDDS. Almost all README files for the SDDS packages still use the name **Tegel Design System**, despite there now being a separate package/repo called **Tegel** that is the "real" **Tegel Design System**.

In order to reduce confusion, I think it would be a good idea to revert the name change in all README files and add deprecation warnings. Similar to what you would find for the documentation on [tegel.scania.com](https://tegel.scania.com/).

![image](https://github.com/scania-digital-design-system/sdds/assets/52670379/5829f98b-6aaf-4f98-b2ff-870d845f983b)

**Comment by theJohnnyMe** [comment]
All old packages are now updated, deprecation status is set + old Storybook has deprecation message too. 
@lkritsimas thanks for raising the issue, I hope so you find it useful too. Please ping us if you think something more can be done from our side.
