### ISSUE TITLE
Bug - React demo, <a href warning

### ISSUE THREAD

**Issue by iths-jonathan-engman** [scania-digital-design-system/sdds#117]
**Describe the bug**  
-- On line 38 in components/main/Main.js, the "a" element doesn't href to anything, and React doesnt like that. If a dummy link 
    is set with href=, like "/" or "/#", the disabled breadcrumb doesn't get "disabled", and becomes clickable.

**To Reproduce**   
-- Pull down the project
-- Initiate the project
-- npm start
-- Open file components/main/Main.js

**Screenshots**  
![image](https://user-images.githubusercontent.com/54362354/112992279-52666280-9168-11eb-93ee-f50ab3d35168.png)
![image](https://user-images.githubusercontent.com/54362354/112992334-5eeabb00-9168-11eb-8c1f-3a563940fa09.png)

**Framework and version**  
-- Framework: React

[AB#719](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/719)

**Comment by mmexvr** [comment]
This is a uncommon case, when you use a breadcrumb you have a flow in the application. 

For example audio > headset > wireless headset. Then the application will have its own way for navigating. This is not something from the component

I will close this issue
