### ISSUE TITLE
SDDS not working with Vue3/Vite

### ISSUE THREAD

**Issue by magnuslundin** [scania-digital-design-system/sdds#125]
**Describe the bug**  
When using Vite (https://vitejs.dev) as bundler for a Vue3 project will SDDS generate errors which stops rendering of the page. 

_ReferenceError: require is not defined
    at @scania_components.js:1726
    at async initializeComponent (@scania_components.js:1421) undefined
consoleError @ index-5cfef938.js:1713
index-5cfef938.js:1366 Uncaught (in promise) TypeError: Cannot read property 'isProxied' of undefined
    at initializeComponent (@scania_components.js:1424)_

The same code works fine in a Vue3 project using Vue CLI.

**To Reproduce**   
1. Generate a shell project in Vue3 using Vite (Instructions at https://vitejs.dev)
2. Follow basic instructions for adding SDDS.
3. Add a <sdds-theme> component and some HTML.
4. Run and check the console

Demo project can be found here: https://gitlab.scania.com/sssmzb/sdds-vue3-vite (internal)

**Expected behavior**  
SDDS in combination with Vue3 should be possible to bundle with Vite.

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Version of SDDS**  
    "@scania/components": "^1.4.2",
    "@scania/theme-light": "^2.1.0",

**Framework and version**  
    "vue": "^3.0.5"
    "vite": "^2.1.5"

**Repo link**  
https://gitlab.scania.com/sssmzb/sdds-vue3-vite

**Desktop information:**  
Chrome 89

[AB#744](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/744)

**Comment by mJarsater** [comment]
Will be solved with the release of @scania/tegel.
