### ISSUE TITLE
Build footprint and tree shaking

### ISSUE THREAD

**Issue by ErikLarsson82** [scania-digital-design-system/sdds#129]
Hi,

We are using these components for the new ICE (External UI).
```
"@scania/theme-light": "2.1.0",
"@scania/components": "1.4.2",
```
Now, we did some digging and found that before using these packages this was our build stats:
<img width="389" alt="Screenshot 2021-04-19 at 13 14 28" src="https://user-images.githubusercontent.com/4123744/115243133-e0f45100-a122-11eb-8e20-9002a4147ca6.png">
And after adding the components.
![image](https://user-images.githubusercontent.com/4123744/115243194-f36e8a80-a122-11eb-9581-bc923742504a.png)
This in turn broke our build pipeline.
![image](https://user-images.githubusercontent.com/4123744/115243261-07b28780-a123-11eb-83c5-2da495cd6153.png)

![image](https://user-images.githubusercontent.com/4123744/115243559-57914e80-a123-11eb-8a54-6a91f0c5f8e1.png)
Are these sizes to be expected? Is there any tree shaking we can do or did we install these incorrectly or something?

Thanks in advance.
/Erik

[AB#761](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/761)

**Comment by mmexvr** [comment]
Sadly, yes... :(

The biggest reason for the size are the icon svg, we have a task to look into a better way to use the icons/seperate it from the theme package it self. That is major reason, we also have some legacy css that we want to get ride off, but that is not something we have look into at all.

Theme/core/icons

Thanks for the report!

**Comment by helloimela** [comment]
Related to #36
