### ISSUE TITLE
Bug - "Font file Not Found error"

### ISSUE THREAD

**Issue by shaheer-scania** [scania-digital-design-system/sdds#133]
**Describe the bug**  
Font file Not Found (404) error when using sdds-schema

**To Reproduce**   
1. Create HTML Project
2. Import SDDS theme and components
```
  <script src="resources/node_modules/@scania/theme-light/dist/light-theme.js"></script>
  <script src="resources/node_modules/@scania/components/dist/core.js"></script>
```
3. Use SDDS theme
`  <sdds-theme></sdds-theme>`

**Screenshots**  
Font Not Found error in the console

**Framework and version**  
    @scania/components": "^1.4.2,
    @scania/theme-light": "^2.1.0",

**Additional context**   
Please fix it as early as possible we are implementing Login page using SDDS theme.
![image](https://user-images.githubusercontent.com/39769211/116038409-b3029580-a669-11eb-93af-88341fc5f10b.png)

The issue is also reproducible in the sample HTML project
https://github.com/scania-digital-design-system/sdds/tree/master/demo/HTML

[AB#783](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/783)

**Comment by mmexvr** [comment]
#108 Replicated issue, will close
