### ISSUE TITLE
Improvement - Text field using name attribute 

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#157]
**Describe current situation**  
_Describe what the current situation and what problem it is causing for this improvement_

Right now it isn't possible to use the name attribute on text fields

**Describe the improvement**  
_A clear and concise description of what kind of improvement you have in mind._
Some users wants the possibility to add name attribute to the input field

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Use the text field element
2. User name attribute with a form
3.  no name attribute is added on the input

**Screenshots**  
_If applicable, add screenshots to help explain your ideas._

**Additional context**  
_Add any other context about the suggestion here._

[AB#872](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/872)

**Comment by digitaldesign-scania** [comment]
Fixed in #159
