### ISSUE TITLE
Bug - Dropdown menu with ampersand (&)

### ISSUE THREAD

**Issue by StaffanSol** [scania-digital-design-system/sdds#175]
**Describe the bug**  
We are trying to use the SDDS dropdown component. However, one of the options in our dropdown list includes a "&" (ex: Staffan & Solin). When having this option in the selection it changes the "&" to "\&amp;"

**To Reproduce**   
_Steps to reproduce the behavior and be very detailed_  

I changed the data from "Stockholm" to "Stockholm & Stockholm" in the codesandbox demo example and the behavior is same there if you try to pick city "Stockholm & Stockholm" in the "City-Dropdown list" but when it is selected the label becomes "Stockholm &amp; Stockholm".

codesandbox link with changed data: https://codesandbox.io/s/boring-feather-lf03n?file=/src/Form/Form.js
1. Go to https://codesandbox.io/s/boring-feather-lf03n?file=/src/Form/Form.js
2. Click on City-dropdown list
3. Select Stockholm & Stockholm 
4. See wrong value as label it will be "Stockholm \&amp; Stockholm" instead of Stockholm & Stockholm

**Expected behavior**  
_A clear and concise description of what you expected to happen._
I would like to see Stockholm & Stockholm in the dropdown menu.

**Version of SDDS or which package**  
Latest

**System information:**  
_Please complete the following information, don't forget version_
Chrome latest

[AB#957](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/957)

**Comment by theJohnnyMe** [comment]
I am working on this one currently. The update is expected to go out next Wednesday.

**Comment by alexlioliopoulos** [comment]
This is fixed in our latest release. I am closing this now.
