### ISSUE TITLE
Bug - "Issue in @scania/components and @scania/theme-light"

### ISSUE THREAD

**Issue by avishek-scania** [scania-digital-design-system/sdds#181]
Hi Team! I installed the two modules below in my angular project as per instruction in sdds/demo/angular at master · scania-digital-design-system/sdds · GitHub

```
npm i @scania/components --save-dev
npm i @scania/theme-light --save-dev
```

But getting the below error for both modules.
```
"Could not find a declaration file for module '@scania/components'. 'c:/.../node_modules/@scania/components/dist/collection/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/scania__components` if it exists or add a new declaration (.d.ts) file containing `declare module '@scania/components';`" 
"Could not find a declaration file for module '@scania/theme-light'. 'c:/.../node_modules/@scania/theme-light/dist/module.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/scania__theme-light` if it exists or add a new declaration (.d.ts) file containing `declare module '@scania/theme-light';`"
```

**To Reproduce**   
1. Install latest Angular version
2. Install the @scania components and theme-light modules
3. Compile/Run the project.

**Expected behavior**  
SDDS modules should work out of the box.

**Version of SDDS or which package**  
Latest version

**System information:**  
 - Framework: Angular v12.1.4
 - Device: Desktop
 - OS: Windows 10
 - Browser: NA

**Additional context**   
https://teams.microsoft.com/l/message/19:1257007a64d44c64954acca27a9d4b46@thread.skype/1628692096338?tenantId=3bc062e4-ac9d-4c17-b4dd-3aad637ff1ac&groupId=79f9bfeb-73e2-424d-9477-b236191ece5e&parentMessageId=1628692096338&teamName=Scania%20Digital%20Design%20System&channelName=General&createdTime=1628692096338

[AB#966](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/966)

**Comment by mmexvr** [comment]
#115 Related

**Comment by georgechamoon** [comment]
did you solve it?
