### ISSUE TITLE
Sdds header Inline menu dropdown functionality

### ISSUE THREAD

**Issue by kshekhar94** [scania-digital-design-system/sdds#182]
**What is your feature request?**  
 The Inline menu in sdds header has dropdown_menu but there isn't a functionality to expand and collapse the menu on click.
So I am requesting to add the click functionality on dropdown menu to expand and collapse the submenus.
Currently we have to write additional javascript code to get the dropdown menu to expand and collapse on click.

**Describe the solution you'd like**  
On click of a dropdown menu the menu should toggle between expanded and collapsed state and also there should be a feature to show another sub-submenu if you hover on the expanded submenu

**Additional context**  
Below is the screenshot of the feature that I am requesting you to add
![Sdds header](https://user-images.githubusercontent.com/81211310/130245213-c4bf8ffa-1a2e-472c-a9a9-dc85b6ab4e22.PNG)

[AB#971](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/971)

**Comment by mJarsater** [comment]
Since this is a html/css component so javascript is shipped. In the upcoming @scania/tegel we will provide this as a web component aswell, which will include the javascript.
