### ISSUE TITLE
Bug - "Link in banner"

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#185]
When I try to add a link in Storybook, it does not happen in a new line, like it is supposed to

What happens:
![image](https://user-images.githubusercontent.com/76053160/130935750-f5bc7819-0b5f-44ae-9632-7c769477ec4a.png)

What should happen (screenshot from SDDS website, code tab banners):
![image](https://user-images.githubusercontent.com/76053160/130935824-eccb7ecc-8f64-41b1-baf5-ee3aca04f8a1.png)

[AB#980](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/980)

Plus, there is an option to edit the prefix. But there should be an icon there not a text.

**Comment by mmexvr** [comment]
<img width="1567" alt="Screenshot 2021-09-21 at 12 52 35" src="https://user-images.githubusercontent.com/35451568/134158456-69cde4a7-db17-498c-9ca7-e817b8372172.png">

This is how the example looks like in storybook if you look at prefix example. I think we just need to update storybook setting a bit on that example

**Comment by mmexvr** [comment]
I will close this for now, reopen if there is any other problem

**Comment by alexlioliopoulos** [comment]
True, you are right!
