### ISSUE TITLE
Bug - No hover state for text area

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#188]
There is no hover state for text area, at least not in Storybook

![image](https://user-images.githubusercontent.com/76053160/130957427-74084013-2968-44df-81f3-ea40d38fb6c6.png)

[AB#983](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/983)

**Comment by mmexvr** [comment]
fixed in #248
