### ISSUE TITLE
Improvement - "Spec tests fail, low test coverage"

### ISSUE THREAD

**Issue by paladin80** [scania-digital-design-system/sdds#242]
**Describe current situation**  
When I run the "npm test" for components from the current master branch, it reposts that 3 of 9 tests are failed.
The code covered by these 9 tests is less then 25%.

**Describe the improvement**  
Add unit-testing step to your CI/CD pipeline. Add more tests to improve the test coverage.

**If applicable, please provide steps to reproduce**
1. Clone repo.
2. Run "npm test" 
3. Run "stencil test --spec --coverage" to view the coverage report.

[AB#1209](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1209)

**Comment by mJarsater** [comment]
There is no current setup for test for @scania/components. This is something we'll focus on after the release of @scania/tegel
