### ISSUE TITLE
Bug - A lot of files in the dist folder (icon component?)

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#246]
**Describe the bug**  
_A clear and concise description of what the bug is._
Using SDDS will import a lot of files in the dist folder, this should be lower. One of the causes is the icon component, each icon has its own module in the icon package. No error is generated but it can cause performance issues

**To Reproduce**   
_Steps to reproduce the behavior and be very detailed_  
1. Install SDDS in angular project
2. Build the angular project
3. Check the dist folder

**Expected behavior**  
_A clear and concise description of what you expected to happen._
Fewer files

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Version of SDDS or which package**  
components 1.5.1

**System information:**  
_Please complete the following information, don't forget version_
 - Framework: angular 12
 - Device: Mac Computer
 - OS: MACOS

**Additional context**   
_Add any other context about the problem here._
Worth looking into either removing or changing the icon component

[AB#1235](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1235)

**Comment by mJarsater** [comment]
This will be fixed with @scania/tegel package.
