### ISSUE TITLE
Bug - "Behind proxy, can not install cz-conventional-changelog"

### ISSUE THREAD

**Issue by gaonita** [scania-digital-design-system/sdds#247]
Issue with installing cz-conventional-changelog.
when I run `npm run commit` the error below appears.

```
Cannot find module 'C:\sdds\node_modules\cz-conventional-changelog'
```
most likely related to the proxy setting 😢 

[AB#1236](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1236)

**Comment by mmexvr** [comment]
Workaround is that we manually write the git commit message
