### ISSUE TITLE
Feature - in colour package provided the src files in scss folder

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#261]
**What is your feature request?**  
_A clear and concise description of what the feature is. Ex. I'm always frustrated when [...]_
In the color package, we have a few scss files, when the package gets complied we merged it to one bigger file in the dist that we publish as an npm package.  Add the option of providing both the bigger scss file and all the other also. 

<img width="259" alt="Screenshot 2021-12-23 at 13 17 01" src="https://user-images.githubusercontent.com/35451568/147239462-3d030329-7130-4149-b65e-ed993399da60.png">

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Copy all the SCSS file into the dist folder

in the complie.js file we merge the src files into one "_colour.scss" under dist 

so under dist/ folder we provide the same file that is the src, making it easier for imports

"Example"
<img width="267" alt="Screenshot 2021-12-23 at 13 18 23" src="https://user-images.githubusercontent.com/35451568/147239589-5186c1d7-e9df-4c29-a827-2819878c5a9f.png">

[AB#1316](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1316)

**Comment by mJarsater** [comment]
This is a feature request that will not be implemented in the SDDS (@scania/components, @scania/colors) packages. If the need persists, feel free to reach out to our PO Johan Nilo.
