### ISSUE TITLE
Feature - Upgrade Storybook version

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#262]
**What is your feature request?**  
_A clear and concise description of what the feature is. Ex. I'm always frustrated when [...]_
Upgrade storybook version to a later one

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
Right now, the versions is pretty far behind the current version of storybook

[AB#1329](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1329)

**Comment by theJohnnyMe** [comment]
It is upgraded to the new version: 6.4.18.
