### ISSUE TITLE
Improvement - Link component hover and visited is the same

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#264]
**Describe current situation**  
_Describe what the current situation and what problem it is causing for this improvement_
The link component in hover state and visited have the same color, which me if the link has been visited then it will no hover effect on the link

**Describe the improvement**  
_A clear and concise description of what kind of improvement you have in mind._
Change color 

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Go to page with our link component
2. Click on it, so it gets visited state
3. Hover over it

**Screenshots**  
_If applicable, add screenshots to help explain your ideas._
<img width="353" alt="Screenshot 2021-12-23 at 15 03 47" src="https://user-images.githubusercontent.com/35451568/147251142-5ddafe4e-0309-480b-895b-c187bf16a880.png">

**Additional context**  
_Add any other context about the suggestion here._
Sync with design

[AB#1336](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1336)

**Comment by alexandereneroth** [comment]
Closing, as this is fixed in @scania/tegel. But please reply if you don't agree with this decision.
