### ISSUE TITLE
Bug - "Repo contains no COPYRIGHT"

### ISSUE THREAD

**Issue by erik78se** [scania-digital-design-system/sdds#273]
This repo contains no copyright statement.

This would be a good thing.

[AB#1373](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1373)

**Comment by mmexvr** [comment]
We have it under https://github.com/scania-digital-design-system/sdds/blob/master/LICENSE
