### ISSUE TITLE
Feature - Add code of conduct

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#277]
**What is your feature request?**  
_A clear and concise description of what the feature is. Ex. I'm always frustrated when [...]_
It would be good to have a code of conduct file here, make sure people follow it :)

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._
https://github.com/scania-digital-design-system/sdds/community

**Additional context**  
_Add any other context or screenshots about the feature request here._

[AB#1377](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1377)

**Comment by mJarsater** [comment]
Will be added.
