### ISSUE TITLE
Bug - Dropdown icon not flipping

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#284]
There is a bug affecting the chevron of our dropdown.

More specifically, when expanding the dropdown, the chevron icon is not getting flipped as it should, but stays as it was before.

![image](https://user-images.githubusercontent.com/76053160/149362567-56bf1f90-2cbc-46a8-9319-a04d27ffeb8e.png)

![image](https://user-images.githubusercontent.com/76053160/149362592-754522a7-5f3e-4c08-b3e1-5c16b21e330d.png)

So pretty much either the animation is not working, or we never had this animation.

[AB#1386](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1386)

[AB#1394](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1394)

**Comment by theJohnnyMe** [comment]
This should be fixed in component: 3.0.0.
