### ISSUE TITLE
Bug - Dropdown 'label-inside' mode doesn't present label as a placeholder

### ISSUE THREAD

**Issue by gaonita** [scania-digital-design-system/sdds#297]
The "label-inside" variant should be like this:

![image](https://user-images.githubusercontent.com/76053160/150353028-7c0bfcc0-49a8-4830-9e0d-323f6c993414.png)

Now it's like this:

![image](https://user-images.githubusercontent.com/76053160/150353083-002767ed-2e1c-4c85-b706-20a95a80b78e.png)

Meaning that in the current version, there is no label present, but we keep showing the "select option" text.

_Originally posted by @alexlioliopoulos in https://github.com/scania-digital-design-system/sdds/issues/286#issuecomment-1017532400_

[AB#1504](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1504)

**Comment by theJohnnyMe** [comment]
This should be fixed in component: 3.0.0.
