### ISSUE TITLE
[Bug report]: Components Library — Missing Tiles

### ISSUE THREAD

**Issue by astrit** [scania-digital-design-system/sdds#322]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components 2.1.0

### Browser

Chrome

### Framework

Plain HTML

### Reproduction steps

1. ComOn Editors link — https://digitaldesign.scania.com/home
![image](https://user-images.githubusercontent.com/2398447/157398507-c5bd346d-d7d4-470f-8c3f-440aaeecfc6b.png)

2. Navigation link "Tiles" — https://www.scania.com/ux-library/en/home.html
![image](https://user-images.githubusercontent.com/2398447/157398650-19269afa-0b14-4f9f-8aa7-7ba4b11ec4f9.png)

3. Sends you to a empty link — https://www.scania.com/ux-library/en/home/tiles.html
![image](https://user-images.githubusercontent.com/2398447/157398737-3487d004-6876-476d-bd88-e7bfb5684658.png)

4. Same goes for the UX Library link on top right of the nav 
![image](https://user-images.githubusercontent.com/2398447/157398928-203ecf68-bd76-4a49-9383-95133d67700e.png)
 

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Either remove or forward to the designated page.

> Note: I did not fork the repo I did see this only from the demo. 

### Console errors

No error. 

### Contact information

am@astrit.co

**Comment by alexlioliopoulos** [comment]
Good catch Astrit! We have now removed these pages.
