### ISSUE TITLE
[Bug report]: Uncaught DOMException causing blank page to be displayed

### ISSUE THREAD

**Issue by JohnKberg** [scania-digital-design-system/sdds#326]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components 1.15.0

### Browser

Chrome

### Framework

.NET

### Version

.NET Framework 4.6

### Reproduction steps

N/A

In some scenarios there is an exception thrown in @scania/components **core.js** when script tag for sdds-components.js is to be inserted in DOM. Possibly due to browser extensions adding script tags into the DOM.

See code example section.

### Code example

Problem is most likely due to the fact that `parentScript[0]` on line 19 below - in some cases - contains a <script> tag that is not a child node of document.head.

### Possible solution ?
On line 2, change:
`const parentScript = doc.querySelectorAll('script');`
to
`const parentScript = doc.head.querySelectorAll('script');`

https://github.com/scania-digital-design-system/sdds/blob/f0f373e8ed00a7cbf12f8932b9cf502cd6e89497/components/src/helpers/core.js#L1-L20

### Screenshots

Page loaded but empty:
![console-error-crop](https://user-images.githubusercontent.com/15640891/158565412-bb6afe75-c3ed-4753-89c5-df955b795290.png)

Users Chrome extensions (possibly causing the problem)
![chrome-extensions-crop](https://user-images.githubusercontent.com/15640891/158566234-9b0e5fc8-b712-4b2b-b94b-93419034adb7.png)

### Expected behaviour

Page loaded without errors even when first <script> in DOM is not part of < head>

### Console errors

core.js:20 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at https://xxxx.yyyyy.com/node_modules/@scania/components/dist/core.js:20:12
    at https://xxxx.yyyyy.com/node_modules/@scania/components/dist/core.js:21:3

**Comment by alexandereneroth** [comment]
Closing this, appears to cover the same issue as the newer https://github.com/scania-digital-design-system/sdds/issues/1019
