### ISSUE TITLE
[Feature Request]: Table sort and pagination event

### ISSUE THREAD

**Issue by dgfreemem** [scania-digital-design-system/sdds#396]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Request 1, sorting
When clicking a sortable column an event should be possible to use. 
The event data should contain column key and sort direction - like onColumnSort( $event ) or onColumnSort(key string, direction string)  .

Request 2 pagination
When clicking next, previous (last, first) button on pagination control an event should be possible to use. The event data should contain the resulting page number - like onPageChange( $event ) or onPageChange( page number ).
I would also like first and last button on the control as well as a way to set the current page like setCurrentPage( 5 )
This would also mean that the number of pages and current page must be handled and set by the client since the dataset for the table would only contain the number of rows for the requested page.

### Background

Since a list sometimes can contain a lot of rows its not always feasible to preload all data to the client (due to latency and db-performance), rather get only the data that fits into the requested page from back-end. This affects both sorting and pagination. I need to know if my requests is something that you can implement otherwise I will have to code them myself.

We have not implemented sorting yet and I would rather wait for the functionality in request 1 since sorting would mean a new query to the back-end. 

For pagination we have a solution working as described in request 2 but I would rather have it available in the SDDS-control itself. 

### Idea

See feature request

### Goals and objectives

To be working as in request 1 and 2

### Timeline

Start of october

### Resources

contact me

### Contact information

dan.granroth@scania.com

**Comment by alexlioliopoulos** [comment]
Thanks a lot for reporting this Dan! We will soon update you on where on our roadmap this will land.

**Comment by nathalielindqvist** [comment]
This has been handled in the new @scania/tegel package, please find a reference in the following link: https://tegel-storybook.netlify.app/?path=/story/components-data-table-web-component--event-listeners
