### ISSUE TITLE
SDDS dropdown toggle dropdown

### ISSUE THREAD

**Issue by dgfreemem** [scania-digital-design-system/sdds#401]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components 4.5

### Browser

Edge (Chromium)

### Framework

Angular

### Version

14

### Reproduction steps

Toggle only works on dropdown and clicking an item in the list but clicking the drop up arrow.

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Ckicking drop up arrow show hide the dropdown list

### Contact information

dan.granroth@scania.com

**Comment by nathalielindqvist** [comment]
This issue has been resolved in the latest versions of both @scania/components and @scania/tegel packages.
