### ISSUE TITLE
[Bug report]: onClick cannot be fired within the sdds-modal component 

### ISSUE THREAD

**Issue by xunih** [scania-digital-design-system/sdds#408]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components 4.5.0

### Browser

Chrome

### Framework

React

### Version

React 13

### Reproduction steps

1. Add component sdds-modal
2. Add a button in the modal
3. Add event onClick to the added button
4. Try to print out some text in the console when the button is clicked 

Note: when trying onMouseOver event, it can be fired. 

### Code example

```
function Test(){
  function clickEventHandler(){
    console.log("button clicked");
  }

  return (
    <sdds-modal size="md" selector="#modalthree" prevent>
      <h5 slot="sdds-modal-headline">Test</h5>
      <div slot="sdds-modal-body">
           <button
             slot="sdds-modal-actions"
             className="sdds-btn sdds-btn-primary sdds-on-white-bg"
             onClick={clickEventHandler}
           >
           Test
           </button>
      </div>
   </sdds-modal>
  );
}
```
### Screenshots

<img width="750" alt="button-bug" src="https://user-images.githubusercontent.com/48941753/178676050-d0821b96-4747-44db-a2c4-bcde4df4bdd4.PNG">

### Expected behaviour

A button within the sdds-modal component should be able to support onClick event.

### Console errors

No warning/error in console

### Contact information

xuni.huang@scania.com

**Comment by mJarsater** [comment]
Fixed in https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponent%404.10.4
