### ISSUE TITLE
[Feature Request]: Ability to reset the selected option for <sdds-dropdown-filter>

### ISSUE THREAD

**Issue by furkick** [scania-digital-design-system/sdds#409]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

The component <sdds-dropdown-filter> does not currently have a way to reset to its default state. Assuming the default state will be something like selected-option null and filter text null/empty.

### Background

We are using a list of options that can be modified. If an item is removed from the list of options then I would like to be able to reset the dropdown to its initial state.

### Idea

Include a method to be able to reset the dropdown or possibly observe when the attribute selectedOption is null and reset the dropdown to its initial state.

### Contact information

christopher.halfpenny@scania.com

**Comment by mJarsater** [comment]
Closed in: https://github.com/scania-digital-design-system/sdds/pull/411
