### ISSUE TITLE
Tab-bug when adding elements

### ISSUE THREAD

**Issue by sssaff** [scania-digital-design-system/sdds#415]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components, @scania/theme-light

### Package versions

components 4.4.2, theme-light 4.3.2

### Browser

Edge (Chromium)

### Framework

Plain HTML

### Reproduction steps

Add a tab to page <sdds-inline-tabs auto-height>...
Add html elements to div inside tab and it gets bugged. Not resizing when overflow.

### Screenshots

Add/Copy screenshot here

### Expected behaviour

div should grow automatically

### Console errors

Add warning/error message

### Contact information

staffan.hedelin@scania.com

**Comment by mJarsater** [comment]
This bug report is added to our backlog, development work is needed. If you have any further questions reach out to our PO, Johan Nilo.
