### ISSUE TITLE
[Feature Request]: More table functionality

### ISSUE THREAD

**Issue by ElviraElmira** [scania-digital-design-system/sdds#428]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

1. In the table component we need the possibility to add custom templates, for example icons or more complex content than just strings. In our case for example dynamic charging indication images/icons.

2. Make it possible to stretch the table to full width of the container (table-layout:fixed, width: 100%)

3. Make it possible to add detail rows in the table (expandable rows)

### Background

We have a lot of complex data tables in My Scania. In our new upcoming service in Charging, we need to show charging status and be able to expand the rows to see more data. 

### Idea

For the full width:  table-layout:fixed, width: 100% on the table.
For the custom template, not sure, you need to provide slots for injecting custom content in columns. Instead of providing header-cells as slotted content maybe whole columns?

### Goals and objectives

To be able to add custom templates and expandable rows into the table, and stretch the table to full width of its container

**Comment by nathalielindqvist** [comment]
All three issues have been resolved in the latest version of the @scania/tegel package. For the complex content you mentioned first, you can now just wrap it with <sdds-body-cell></sdds-body-cell> as that one has a slot, so you can pass whatever content you'd like to it. The[ full width ](https://tegel-storybook.netlify.app/?path=/story/components-data-table-web-component--default&args=responsiveDesign:true)option for the data table container is also available at your convenience. Along with this you can also find an example for [expandable rows](https://tegel-storybook.netlify.app/?path=/story/components-data-table-web-component--expandable-rows).
