### ISSUE TITLE
z-index of sidemenu higher than overlay

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#434]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

website

### Browser

Chrome

### Framework

Angular

### Reproduction steps

The overlay should also be on top of the side menu

![image](https://user-images.githubusercontent.com/76053160/188137852-936bf7ef-de96-41b3-8e95-81b5318898ee.png)

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Component x should be able to...

### Console errors

Add warning/error message

[AB#2323](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2323)

**Comment by alexandereneroth** [comment]
Closing, as this issue is very old and looks like it's solved already.
With the current modal implementation, whether its backdrop appears above the side menu or not would depend on where it is placed in the DOM.

**Comment by alexlioliopoulos** [comment]
@alexandereneroth Hej Alexander! The issue is probably solved on a component level, but it still there in the Tegel website, exactly as seen in the screenshot of this ticket.

**Comment by alexandereneroth** [comment]
Good shout! I'll try to add a issue/ fix it on the website repo
