### ISSUE TITLE
[Feature Request]: sdds-modal - increase max-height or allow for a custom value

### ISSUE THREAD

**Issue by joakimglaving** [scania-digital-design-system/sdds#487]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

In the latest release (4.9.2), a "testing scrollable modal" commit was included, which made things go from [this (before)](https://user-images.githubusercontent.com/8373600/194807551-da7678af-b205-4e58-a431-8008d218c54e.png) to
[this (after)](https://user-images.githubusercontent.com/8373600/194807415-18b10fe8-245b-4675-bdcc-df7bf05f365a.png).

It would be really nice if you could increase the max-height, 60vh is far too little. Let it use more of the available space, like 90vh or something, or allow the user to insert a custom value for the breakpoint.

### Background

We show an image preview from Image Service before the user proceeds. This image preview "broke" with release 4.9.2 as the modal is only allowed to take up 60vh max-height.

[AB#2371](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2371)

**Comment by johan-scania** [comment]
Solved in #1037
