### ISSUE TITLE
[Bug report]: Dropdown using default-option selects the wrong option.

### ISSUE THREAD

**Issue by thezic** [scania-digital-design-system/sdds#493]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components 4.9.3

### Browser

Edge (Chromium)

### Framework

React

### Version

React 18

### Reproduction steps

Set default-option on the dropdown

See codebox for example:
https://codesandbox.io/s/tegel-dropdown-test-wqzyqo?file=/src/App.tsx

### Code example

    export default function App() {
      const data = `[
        {"label": "Denmark","value":"1384"},
        {"label": "Sweden","value":"4"}]`;
      return (
        <div className="App">
          {/* 1384 is Denmark, but Sweden is selected in the dropdown*/}
          <sdds-dropdown-filter data={data} default-option="1384" />
        </div>
      );
    }

### Screenshots

![image](https://user-images.githubusercontent.com/215692/195299281-36768a82-578b-40ed-bd7b-a94b00e1d7c1.png)

### Expected behaviour

The dropdown should select the correct option.

### Contact information

simon.dahlberg@cdab.eu

[AB#2427](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2427)

**Comment by thezic** [comment]
It is due to this line:
https://github.com/scania-digital-design-system/sdds/blob/22fc47bf15f909f5fe4d9c8fb9e02b5af3dc5dd2/components/src/components/dropdown/dropdown.tsx#L115

Essentially you check if the value on the option is a substring of the option we want to set. And that is true for the above example. `"1384".includes("4") === true`

**Comment by nonameolsson** [comment]
Den här verkar ha blivit löst, och kommer med i nästa release https://github.com/scania-digital-design-system/sdds/pull/617

**Comment by mJarsater** [comment]
Closed in https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponents%404.10.2
