### ISSUE TITLE
[Bug report]: sdds-text-field error state conflict with sdds-helper slot text.

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/sdds#524]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/tegel-old

### Package versions

@scania/components@4.10.0

### Browser

Chrome

### Framework

Angular

### Reproduction steps

1. Create an sdds-textfield
2. Set it state to error
3. Add a span which will slot to sdds-helper

The error state exclamation icon will push both the helper text and the char count below where they should be.

### Code example

<div>....

### Expected behaviour

Component should render the helper text and not break the position of other information.

### Console errors

Add warning/error message

### Contact information

thiago.oliveira@scania.com

[AB#2443](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2443)

**Comment by mJarsater** [comment]
Closed in: https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponents%404.10.1
