### ISSUE TITLE
Dropdown label and text placement

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds#550]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/tegel-old

### Package versions

Storybook

### Browser

Chrome

### Framework

Other

### Reproduction steps

Storybook

![image](https://user-images.githubusercontent.com/76053160/198352401-b7557137-3498-4f75-aadf-70258af3915f.png)

Documentation

![image](https://user-images.githubusercontent.com/76053160/198352467-1b11a748-880a-4d49-ae8d-02c46146e134.png)

The padding-bottom of the dropdown large is 20px in Storybook, but is designed to be 16px. The padding top is also wrong, but I cannot see the actual pixel number from the inspection tool.

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Component x should be able to...

### Console errors

Add warning/error message

[AB#2463](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2463)

**Comment by mJarsater** [comment]
Fixed in https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponent%404.10.4
