### ISSUE TITLE
Bug - Storybook some times failed to start with lerna command

### ISSUE THREAD

**Issue by helloimela** [scania-digital-design-system/sdds#57]
**Describe the bug**  
When components dependency for scania theme linked to local work, storybook failed to start on lerna command "lerna run start --parallel".
Maybe because the build in theme is not done before storybook build.
Notice that when we have @scania-sdds package, everything works fine. 
Maybe good to have --stream flag instead.

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Go to sdds project
2. Run npm i then npm start
3. See if storybook built & running

**Expected behavior**  
Theme should be built before storybook with lerna command

**Version of SDDS**  
1.0.0

**Desktop information:**  
_Please complete the following information_

 - OS:  Windows 10

[AB#331](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/331)

**Comment by mmexvr** [comment]
Not valid anymore
