### ISSUE TITLE
[Feature Request]: Add disabled option to sdds-dropdown-option element

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/sdds#589]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Sometimes we wish to show options that aren't actually available for the user to select them in the current context.
Using the native option element one can add a disable option to still show the option to the user, but make it unavailable for selection, this request is to add a similar feature to the sdds-dropdown-option.

### Background

Some applications use the native select/option disable option to show the user that one option is not available in the current context. We need similar funcionality if we are to move to sdds.

### Idea

Add a disabled option, the item would still be shown in the dropdown, but the element would have a different styling and clicking it would not trigger the selected event.

### Contact information

thiago.oliveira@scania.com

[AB#2549](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2549)

**Comment by mJarsater** [comment]
Added in https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponent%404.10.4
