### ISSUE TITLE
Improvement - Move c-theme under core instead of patterns

### ISSUE THREAD

**Issue by helloimela** [scania-digital-design-system/sdds#59]
**Describe current situation**  
c-theme file is under "patterns" folder in theme project

**Describe the improvement**  
c-theme should belongs to core, since it is a core that contains all components classes & styles.

Need to check gulpfile.js to see if it's still added to the store when moved to core

[AB#332](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/332)

**Comment by mmexvr** [comment]
Closing this, need to look at the theme component in general
