### ISSUE TITLE
[Bug report]: On the sdds-banner component, when the error takes more than 100% width, the "close" icon gets super small

### ISSUE THREAD

**Issue by thomasmorice** [scania-digital-design-system/sdds#619]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/theme-light

### Package versions

@scania/components 4.7.0

### Browser

Chrome

### Framework

React

### Reproduction steps

1. Use sdds-banner with a very long message in it so it has to jump into a new line
2. See the close icon being very small

### Code example

<div>....

### Screenshots

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/82149830/202702102-325c4da9-56d8-4b60-80ac-b8692ff18949.png">

### Expected behaviour

The icon should remain the same size whether if the text is on one line or multiple

### Console errors

Add warning/error message

[AB#2605](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2605)

**Comment by mJarsater** [comment]
Closed in https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponents%404.10.2
