### ISSUE TITLE
Improvement - Show the cursor: not-allowed on components disabled

### ISSUE THREAD

**Issue by helloimela** [scania-digital-design-system/sdds#71]
**Describe current situation**  
On disabled state we have default cursor

**Describe the improvement**  
On disabled state for all components, should show not-allowed cursor.

[AB#368](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/368)

**Comment by mmexvr** [comment]
Closing this for future issues, might depend on the component
