### ISSUE TITLE
[Feature Request]: add property to show/hide X (close) button on sdds_modal

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/sdds#750]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

In some situations I would like to control how the user closes a modal/dialog so he is forced to use the action buttons so the application doesn't enter an inconsistent state. As there is no callback option when the dialog is closed, giving an option to hide the X on the right top corner of the modal would be great.

### Background

Make the migration easier when implementing existing application behaviors.

### Contact information

thiago.oliveira@scania.com

**Comment by mJarsater** [comment]
Hi! It is a UX decision to always have a close button on the modal, and therefor we will not be implementing this.

**Comment by toliv3** [comment]
Hi, if you guys don't want to implement a simple feature like this, at least implement a closeModalEvent that is triggered when that X button is invoked. The way the current modal works it lacks programmatic control over its actions and that makes it hard to migrate existing functionality to sdds/tegel.

**Comment by toliv3** [comment]
Opened issue: https://github.com/scania-digital-design-system/sdds/issues/759

**Comment by mJarsater** [comment]
> Hi, if you guys don't want to implement a simple feature like this, at least implement a closeModalEvent that is triggered when that X button is invoked. The way the current modal works it lacks programmatic control over its actions and that makes it hard to migrate existing functionality to sdds/tegel.

I will take that feature request to the team and we'll see what we can do.
