### ISSUE TITLE
[Feature Request]: Trigger onModalCloseEvent when hitting the X button on modals.

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/sdds#759]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Trigger an event (suggestion: onModalCloseEvent) when hitting the X button so we can have programmatic control over what happens in the modal.

### Background

The current modal lacks programmatic control. We need to have control of what happens to be able to migrate existing functionality to sdds/tegel.

### Contact information

thiago.oliveira@scania.com

**Comment by mJarsater** [comment]
Fixed in: https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponents%404.10.7

The events is called `sddsClose`
