### ISSUE TITLE
[Feature Request]: Possibility to add link columns to sdds-table

### ISSUE THREAD

**Issue by Ansar99** [scania-digital-design-system/sdds#810]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Need a way to add the anchor tag in specific column using the web component version of sdds-table. As of the moment it is not possible to solve this using the body-data prop. 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/47626732/215476851-c4f88f9e-58ea-4603-a3b5-1ac14c042432.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/47626732/215477366-f949b1b3-8c17-4f60-b1d8-9f6b0a620de2.png">

### Background

I need this since I still want to use the functionalities that are already built into the web component version of the sdds-table such as the filtering and sorting functions.

### Idea

Just a spontaneous thought:

A common way to display array/lists of data is to use a map function.
So one possible way might be to specify columns as a prop within the sdds-table component, the children of sdds-table would then consist of a map function that maps the data to each specific column e.g by using the sdds-header-cell instead of passing a body-data props. That way one could chose to either use the body-data props, or passing children components, ultimately resulting in a way for developers to pass anchor tags as childrens to the sdds-header-cell component.

NOTE: I don't know if this solution is viable.

### Goals and objectives

Being able to use links within the data table

### Contact information

ansar.99@hotmail.com

**Comment by mJarsater** [comment]
Great feature request! We'll add it to the backlog.

**Comment by nathalielindqvist** [comment]
This functionality has been added to the latest version of the @scania/tegel package by the use of <slot>.
