### ISSUE TITLE
Improvement - Lerna improvements and ideas

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#82]
**Describe current situation**  
_Describe what the current situation and what problem it is causing for this improvement_

There are some improvement that can be made and some ideas that might be good to look into regarding lerna

**Describe the improvement**  
_A clear and concise description of what kind of improvement you have in mind._

- Not publish tags for each packages
- Remove the command from package.json and just use lerna commands directly (idea)
- Improvement for lerna config , might be needed
- How it detect changes in the packages
- Error when publishing from master branch(Might be solved on a seperate branch)

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. run NPM run publish command
2. It will detect all versions needs an update

**Screenshots**  
_If applicable, add screenshots to help explain your ideas._

**Additional context**  
_Add any other context about the suggestion here._

[AB#479](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/479)

**Comment by mJarsater** [comment]
Not relevant, due to us moving to one package to rule them all.
