### ISSUE TITLE
[Bug report]: Textarea not scrollable when readonly

### ISSUE THREAD

**Issue by Ruddy2007** [scania-digital-design-system/sdds#906]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

4.10.6

### Browser

Chrome

### Framework

Angular

### Reproduction steps

1. Get a text area with a lot of text in it (multiple lines so it becomes scrollable)
2. Make it readonly
3. Try to scroll or make the textarea bigger

This looks to be the issue: https://github.com/scania-digital-design-system/sdds/pull/384/files#diff-15e9c39c65b1a2c1f01246775ea8b510e69eb147d5d46495bd6836dfe3d3a5beR193

### Code example

    <sdds-textarea
      readonly
      value="Hello &NewLine;Hello &NewLine;Hello &NewLine;Hello &NewLine;Hello &NewLine;Hello &NewLine;Hello &NewLine;Hello &NewLine;"
    ></sdds-textarea>

### Screenshots

![image](https://user-images.githubusercontent.com/13089175/223094432-578aa21c-1bad-4a9d-879a-01d86893764b.png)

### Expected behaviour

You should be able to scroll the text area and make it bigger/smaller

### Console errors

Add warning/error message

**Comment by mJarsater** [comment]
Thanks for reaching out! I'll add this to our backlog.

**Comment by mJarsater** [comment]
Fixed in: https://github.com/scania-digital-design-system/sdds/releases/tag/%40scania%2Fcomponents%404.10.7
